import type { Product } from './types';

let catalog: Product[] | null = null;
let productMap: Map<string, Product> | null = null;

export function getCatalog(): Product[] {
  if (!catalog) {
    // catalog.json is generated by preprocess_catalog.py at the project root
    catalog = require('../../catalog.json') as Product[];
  }
  return catalog;
}

export function getProductMap(): Map<string, Product> {
  if (!productMap) {
    const items = getCatalog();
    productMap = new Map();
    for (const p of items) {
      productMap.set(p.product_id, p);
    }
  }
  return productMap;
}

export function lookupById(productId: string): Product | undefined {
  return getProductMap().get(productId);
}
